apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: resilioops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: resilioops-backend:1.0

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: postgres

            - name: REDIS_HOST
              value: redis